# WS 2020/2021

## Aufgabe 1 (Python)

### (a)

In [1]:
r = 'Hallo Welt hier bin ich'.split()[:-2]
print( "Result:\t\t" + str( r ) )

Result:		['Hallo', 'Welt', 'hier']


### (b)

In [2]:
r = [ x for x in 'Hallo welt hier bin ich'.split() ]
print( "Result:\t\t" + str( r ) )

r = max( [ x for x in 'Hallo welt hier bin ich'.split() ] )
print( "Result:\t\t" + str( r ) )

Result:		['Hallo', 'welt', 'hier', 'bin', 'ich']
Result:		welt


### (c)

In [3]:
r = ( 12 + 12 ) * 2
print( "Result:\t\t" + str( r ) )

Result:		48


### (d)

In [4]:
print( "Result:\t\t")
( lambda x, y: x + 2 )( 10 )   

Result:		


TypeError: <lambda>() missing 1 required positional argument: 'y'

### (e)

In [5]:
r = [ 1 ] + [ 2 ]
print( "Result:\t\t" + str( r ) )

Result:		[1, 2]


### (f)

In [3]:
r = ( 1 + 1 ) * '1+2'
print( "Result:\t\t" + str( r ) )

Result:		1+21+2


### (g)

In [7]:
r = str( 10 ** 10 )
print( "Result:\t\t" + r )

r = str( 10 ** 10 )[ :2 ]
print( "Result:\t\t" + r )

Result:		10000000000
Result:		10


### (h)

In [8]:
r = 'hallo'[::-1]
print( "Result:\t\t" + str( r ) )

Result:		ollah


## Aufgabe 2 (R lang)

### (a)

In [1]:
r = c( 3, 5 ) - c( 3, 1 )
cat( "Result:\t\t", r )

Result:		 0 4

### (b)

In [2]:
r = c( 1, 5 ) %in% c( 1, 2, 0, 4, 1, 7, 9 )
cat( "Result:\t\t", r )

Result:		 TRUE FALSE

### (c)

In [3]:
r = c( 2, 1, 4, 11 ) * c( 0, 3 )
cat( "Result:\t\t", r )

Result:		 0 3 0 33

### (d)

In [4]:
r = 1:6
cat( "Result 1:6:\t", r, "\n" )

r = 1:2
cat( "Result 1:2:\t", r, "\n" )

r = 1:6 / 1:2
cat( "Result:\t\t", r )

Result 1:6:	 1 2 3 4 5 6 
Result 1:2:	 1 2 
Result:		 1 1 3 2 5 3

### (e)

In [5]:
r = ( 1:10 )
cat( "Result (1:10):\t", r, "\n" )

r = 1:5 * 2
cat( "Result 1:5*2:\t", r, "\n" )

r = ( 1:10 )[ 1:5 * 2 ]
cat( "Result:\t\t", r, "\n" )

r = ( 1:10 )[ 1:5 * 2 ] * 2
cat( "Result:\t\t", r )

Result (1:10):	 1 2 3 4 5 6 7 8 9 10 
Result 1:5*2:	 2 4 6 8 10 
Result:		 2 4 6 8 10 
Result:		 4 8 12 16 20

### (f)

In [6]:
r = strsplit( "HalliHallo", "" )
cat( "Result:\n" ) 
print( r )

r = table( strsplit( "HalliHallo", "" ) )
cat("Result:\n" )
print( r )

Result:
[[1]]
 [1] "H" "a" "l" "l" "i" "H" "a" "l" "l" "o"

Result:

H a i l o 
2 2 1 4 1 


### (g)

In [7]:
cat( "Result:\n" )
matrix( 1:10, ncol=5 )

Result:


[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

### (h)

In [8]:
r = c( 1, 2, 3, 1, 2, 2 )
cat( "Result:\t\t", r, "\n" )

cat( "Result 1:\n" )
table( c( 1, 2, 3, 1, 2, 2 ) )

cat( "Result 2:\n" )
table( c( 1, 2, 3, 1, 2, 2 ) ) * 4 

Result:		 1 2 3 1 2 2 
Result 1:



1 2 3 
2 3 1 

Result 2:



 1  2  3 
 8 12  4 

### (i)

In [9]:
r = sapply( c( 1, 2, 3 ), function( x ) x + 3 )
cat( "Result:\t\t", r)

Result:		 4 5 6

### (j)

In [14]:
r = rep( "A", 4 )
cat( "rep:\t\t", r, "\n" )

r = factor( c( rep( "A", 4 ), rep( "B", 6 ) ) )
cat( "factor:\t\t", r, "\n" )
           
r = tapply( 1:10, factor( c( rep( "A", 4 ), rep( "B", 6 ) ) ), max )
cat( "Result:\t\t", r )

rep:		 A A A A 
factor:		 1 1 1 1 2 2 2 2 2 2 
Result:		 4 10

## Aufgabe 3 (Numpy)

In [13]:
#!pip3 install numpy
#!pip3 install pandas
#!pip3 install matplotlib

import numpy as np
import pandas as pd
%matplotlib inline

### (a)

In [22]:
r = np.arange( 11 )
print( "Arange:\t\t" + str( r ) )

r = np.arange( 11 )**2
print( "Result 1:\t" + str( r ) )

rr = r[ r%2 == 0 ]
print( "Result 2:\t" + str( rr ) )

Arange:		[ 0  1  2  3  4  5  6  7  8  9 10]
Result 1:	[  0   1   4   9  16  25  36  49  64  81 100]
Result 2:	[  0   4  16  36  64 100]


### (b)

In [46]:
r = np.arange( 1000 )
print( "Arange:\t\t" + str( r[:5] ) + '...' )

r = r[ ( r%3 == 0 ) & ( r%4 == 0 ) & ( r%9 != 0 ) ]
print( "Result:\t\t" + str( r[:5] ) + '...') 

Arange:		[0 1 2 3 4]...
Result:		[12 24 48 60 84]...


### (c)

In [47]:
r = np.arange( 1000 )
print( "Arange:\t\t" + str( r[:5] ) + '...' )

r = ( ( r%10 == 1 ) & ( r%11 != 0 ) )
print( "Boolean:\t" + str( r[:5] ) + '...' )

r =  ( ( r%10 == 1 ) & ( r%11 != 0 ) ).sum()
print( "Result:\t\t" + str( r ) )

Arange:		[0 1 2 3 4]...
Boolean:	[False  True False False False]...
Result:		91


## Aufgabe 4 (Numpy)

### (a)

In [65]:
r = np.random.randint( 0, 1000, 100)
print( "Values:\t\t" + str( r[:5] ) + ' ...' )

r = r[ r < 50 ]
print( "Result:\t\t" + str( r ) )

Values:		[553 838 429 305 323] ...
Result:		[23 28 38 27]


### (b)

In [66]:
r = np.random.randint( 0, 1000, 100)
print( "Values:\t\t" + str( r[:5] ) + ' ...' )

r = r[ r ** 2 % 16 == 0 ]
print( "Result:\t\t" + str( r[:5] ) + ' ...' )

Values:		[617 928 527  62 570] ...
Result:		[928 352 864  64 804] ...


### (c)

In [72]:
r = np.random.randint( 0, 1000, 100)
print( "Values:\t\t" + str( r[:5] ) + ' ...' )

r = x[ -10: ]
print( "Selektion:\t" + str( r[:5] ) + ' ...' )

r = x[ -10: ].mean()
print( "Selektion:\t" + str( r ) )

Values:		[922 253 241 572 580] ...
Selektion:	[774 992 147 960  74] ...
Selektion:	568.1


### (d)

In [78]:
r = np.random.randint( 0, 1000, 100)
print( "Values:\t\t" + str( r[:5] ) + ' ...' )

rr = r - r.mean()
print( "Result:\t\t" + str( rr[:5] ) + ' ...' )

Values:		[664 231 606 232 468] ...
Result:		[ 184.56 -248.44  126.56 -247.44  -11.44] ...


### (e)

In [80]:
r = np.random.randint( 0, 1000, 100)
print( "Values:\t\t" + str( r[:5] ) + ' ...' )

rr = np.absolute ( r - r.mean() ) > 10
print( "Result:\t\t" + str( rr[:5] ) + ' ...' )

Values:		[154 312 252 458 943] ...
Result:		[ True  True  True  True  True] ...


### (f)

In [95]:
r = np.random.randint( 0, 1000, 100)
print( "Values:\t\t" + str( r[:5] ) + ' ...' )

rr = np.quantile( r, [ 0.25, 0.75 ] )
print( "np.quantile:\t" + str( rr ) )

iqr = rr[ 1 ] - rr[ 0 ]
print( "iqr:\t\t" + str( iqr ) )

r = ( np.absolute( r - r.mean() ) > iqr ).sum()
print( "Result:\t\t" + str( r ) )

Values:		[377 523 413 546 925] ...
np.quantile:	[276.25 770.25]
iqr:		494.0
Result:		3


### (g)

In [104]:
r = np.random.randint( 0, 1000, 100 )
print( "Values:\t\t" + str( r[:5] ) + ' ...' )

r = x[1:] == x[:-1]
print( "Result:\t\t" + str( r[:5] ) + ' ...' )

r = ( x[1:] == x[:-1] ).sum()
print( "Result:\t\t" + str( r ) )

Values:		[ 56 979  49 153 455] ...
Result:		[False False False False False] ...
Result:		1


## Aufgabe 5 (List Comprehension)

### (a)

In [127]:
path = './../../sources/bibel.txt'
r = open( path, "r", encoding="latin-1" ).readlines()[ -2: ] 
print( "Result:\t\t" + str( r ) )

Result:		['\n', '\n']


### (b)

In [129]:
path = './../../sources/bibel.txt'
r = open( path, "r", encoding="latin-1" ).readlines()[ 3 ].split()[ -1 ] 
print( "Result:\t\t" + str( r ) )

Result:		Finsternis


### (c)

In [135]:
path = './../../sources/bibel.txt'
r = [ line for line in open( path, "r", encoding="latin-1" ) if len( line ) > 1 and line[-2] in ",;.?!" ]
print( "Result:\t\t" + str( r[:5] ) + ' ...' )

Result:		['Am Anfang schuf Gott Himmel und Erde.\n', 'Und die Erde war wüst und leer, und es war finster auf der Tiefe; und der Geist Gottes schwebte auf dem Wasser.\n', 'Und Gott sprach Es werde Licht! und es ward Licht.\n', 'und nannte das Licht Tag und die Finsternis Nacht. Da ward aus Abend und Morgen der erste Tag.\n', 'Und Gott sprach Es werde eine Feste zwischen den Wassern, und die sei ein Unterschied zwischen den Wassern.\n'] ...


### (d)

In [137]:
path = './../../sources/bibel.txt'
r = [ line for line in open( path, "r", encoding="latin-1" ) if line.startswith('A')][:3]
print( "Result:\t\t" + str( r[:5] ) + ' ...' )

Result:		['Am Anfang schuf Gott Himmel und Erde.\n', 'Also ward vollendet Himmel und Erde mit ihrem ganzen Heer.\n', 'Also ist Himmel und Erde geworden, da sie geschaffen sind, zu der Zeit, da Gott der HErr Erde und Himmel machte.\n'] ...


### (e)

In [140]:
path = './../../sources/bibel.txt'
r = [ line for line in open( path, "r", encoding="latin-1" ) if len( line ) > 10 ][:4]
print( "Result:\t\t" + str( r[:5] ) + ' ...' )

Result:		['Am Anfang schuf Gott Himmel und Erde.\n', 'Und die Erde war wüst und leer, und es war finster auf der Tiefe; und der Geist Gottes schwebte auf dem Wasser.\n', 'Und Gott sprach Es werde Licht! und es ward Licht.\n', 'Und Gott sah, dass das Licht gut war. Da schied Gott das Licht von der Finsternis\n'] ...


### (f)

In [155]:
path = './../../sources/bibel.txt'
r = [ ( len( line ), i ) for i, line in enumerate( open( path, "r", encoding="latin-1" ) ) ]
print( "List:\t\t" + str( r[:5] ) + ' ...' )

r = max( [ ( len( line ), i ) for i, line in enumerate( open( path, "r", encoding="latin-1" ) ) ] ) 
print( "Max:\t\t" + str( r ) )

r = max( [ ( len( line ), i ) for i, line in enumerate( open( path, "r", encoding="latin-1" ) ) ] )[ 1 ]
print( "Result:\t\t" + str( r ) )

List:		[(38, 0), (112, 1), (51, 2), (82, 3), (95, 4)] ...
Max:		(450, 12829)
Result:		12829


### (g)

In [161]:
r = [ w for w in open( path, "r", encoding="latin-1" ).read().split() if len( w ) > 15 ]
print( "Max:\t\t" + str( r[:3] ) + ' ...' )

r = len( [ w for w in open( path, "r", encoding="latin-1" ).read().split() if len( w ) > 15 ] )
print( "Result:\t\t" + str( r ) )

Max:		['möge.<RF>Wörtlich', 'siebenundsiebzigmal.', 'hundertunddreißig'] ...
Result:		818


### (h)

In [167]:
r = len( [ _ for line in open( path, "r", encoding="latin-1" ) if len( line.split()) > 15 ] )
print( "Result:\t\t" + str( r ) )

Result:		22676


### (i)

In [171]:
r = max( [ (len(line.split()), line)  for line in open( path, "r", encoding="latin-1" ) ] )[ 1 ]
print( "Result:\t\t" + str( r ) )

Result:		Und darnach, spricht der HErr, will ich Zedekia, den König Judas, samt seinen Knechten und dem Volk, das in dieser Stadt vor der Pestilenz, vor Schwert und Hunger übrigbleiben wird, geben in die Hände Nebukadnezars, des Königs zu Babel, und in die Hände ihrer Feinde, und in die Hände derer, die ihnen nach dem Leben stehen, dass er sie mit der Schärfe des Schwerts also schlage, dass kein Schonen noch Gnade noch Barmherzigkeit da sei.



### (j)

### (k)

In [172]:
r = [ i for i, line in enumerate( open( path, "r", encoding="latin-1" ) ) if len(line) <= 1 ]
print( "Result:\t\t" + str( r ) )

Result:		[31173, 31174]


## Aufgabe 7 (Numpy)

### (a)

In [177]:
r = np.random.randint( 1, 10, 54 ).reshape( 9, 6 )
print( "Result:\n" + str( r ) )

Result:
[[7 6 1 3 6 6]
 [3 3 2 4 7 9]
 [6 5 8 3 6 9]
 [3 1 7 7 9 9]
 [5 1 2 3 8 7]
 [5 3 2 5 6 8]
 [5 4 3 9 6 1]
 [2 7 4 9 4 7]
 [7 8 2 9 5 6]]


### (b)

In [183]:
r = np.random.randint( 1, 10, 54 ).reshape( 9, 6 )

rr = ( r==1 ).sum()
print( "Result:\t\t" + str( rr ) )

Result:		6


### (c)

In [189]:
r = np.random.randint( 1, 10, 54 ).reshape( 9, 6 )
rr = ( r[ :, 3 ] == 1 ).sum()
print( "Result:\t\t" + str( rr ) )

Result:		2


### (d)

In [207]:
r = np.random.randint( 1, 10, 54 ).reshape( 9, 6 )
r = r[ r[ :, 3 ] < 5, : ]
print( "Result:\n" + str( r ) )

Result:
[[9 1 9 4 2 9]
 [8 7 8 1 4 9]
 [4 4 7 1 1 8]
 [6 5 1 3 7 7]]


### (e)

In [209]:
r = np.random.randint( 1, 10, 54 ).reshape( 9, 6 )
r = r[ :, r[ -1, : ] < 5 ]
print( "Result:\n" + str( r ) )

Result:
[[8 5 7]
 [5 2 3]
 [2 1 4]
 [2 1 4]
 [1 8 9]
 [4 8 9]
 [7 1 2]
 [5 9 6]
 [2 2 1]]


## Aufgabe 8 (Pandas)

### (a)

In [ ]:
df.loc[ df["stgEnde"] == "S", "stgEnde" ] = "y"

### (b)

In [ ]:
( df.frm == "B" ).sum()

### (c)

In [ ]:
( df.avg > 30.0 ).sum()

### (d)

In [ ]:
df.hzb /= 10
df.iloc[ ( df.avg - df.hzb ).abs().argmax(), : ]

### (e)

In [ ]:
df.groupby('stgName').count().mtknr.plot(kind="bar")

### (f)

In [ ]:
df.groupby("geschl").avg.mean()

### (g)

In [ ]:
df.groupby("stgName").avg.mean()

### (h)

In [ ]:
df.avg.plot(kind="hist")

## Aufgabe 9 (Pandas)

### (a)

In [ ]:
mtcars.index[ mtcars.hp < 60 ]

### (b)

In [ ]:
mtcars[ mtcars.hp > 150 ]].mpg.mean() < mtcars[mtcars.hp < 100].mpg.mean()

### (c)

In [ ]:
mtcars.groupby('cyl').mpg.mean()

### (d)

In [ ]:
mtcars2 = mtcars
mtcars2.wt *= 0.45